# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 09:35
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='primary_image_url',
        ),
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.ImageField(null=True, upload_to='images/reward/'),
        ),
        migrations.AlterField(
            model_name='stationimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/station/', location='/home/kuoteng/smart_campus/smart_campus/smart_campus/media/station/'), upload_to='images/station/'),
        ),
    ]
