# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170911_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationimage',
            name='image',
            field=models.ImageField(upload_to='images/station/'),
        ),
    ]
