# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reward_related_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='related_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Station'),
        ),
    ]
