# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171020_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='visited_beacons',
        ),
    ]
