# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_visited_beacons'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVisitedBeacons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Beacon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='visited_beacons',
            field=models.ManyToManyField(through='app.UserVisitedBeacons', to='app.Beacon'),
        ),
    ]
