# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170819_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.ImageField(null=True, upload_to='app/images/reward/'),
        ),
        migrations.AlterField(
            model_name='stationimage',
            name='image',
            field=models.ImageField(upload_to='app/images/station/'),
        ),
    ]
