# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170823_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationimage',
            name='image',
            field=models.ImageField(upload_to='../../images/station/'),
        ),
    ]
