# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170823_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.ImageField(null=True, upload_to='../../images/reward/'),
        ),
    ]
